// <auto-generated />
using CrabSenseBE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CrabSenseBE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905140000_FarmingRowKhuFields")]
    partial class FarmingRowKhuFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot intentionally omitted — schema changes applied in Up().
            // Full model snapshot remains in AppDbContextModelSnapshot.
        }
    }
}
